Content
deprov447/cse-fresher-website pull request #50
Opened 2020-11-19 15:33 UTC by deprov447

## Content added

#49 issue solved

It is requested to please have thorough proofreading of content and make/suggest appropriate changes. Point to keep in mind: punctuations, cases, grammar, spelling, etc.

2020-11-19 18:59 UTC, MerylinShivangini requested changes
Change in caption for image 3

2020-11-21 15:31 UTC, Sandeepan-Das approved these changes

2020-11-21 18:28 UTC, shruti1421 approved these changes

2020-11-22 06:05 UTC, yasht01 commented on frontEnd/public/index.ejs
> +          <h2 class="rellax" data-rellax-speed="-1">Welcome Muggles</h2>
Welcome Muggles or Welcome Muggies?

2020-11-22 10:06 UTC, adhi-2311 approved these changes

2020-11-23 04:48 UTC, merged